---
title: "Prática-2-R"
João Pedro Moro Bolognini
---
Paleta de cores
```{r}
library("RColorBrewer")
```

Leitura dos dados
```{r}
dados = read.csv('dados.csv', sep=";")
head(dados)
```

Visualização das colunas do conjunto de dados
```{r}
#summary(dados$CODIGO)  # Número de identificação
#summary(dados$MUNICIPIO)  # Cidades
summary(dados$PIB)  # PIB dessas cidades
summary(dados$VALOREMPENHO)  # Valor empenho dessas cidades
```

Como objeto de estudo temos as variáveis numéricos. Vamos criar gráficos para elas.
```{r}
# Boxplots
boxplot(dados$PIB, main="Valores do PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline=F)
boxplot(dados$VALOREMPENHO, main="Valores de empenho", col = brewer.pal(n = 3, name = "Paired"), outline=F)
# Histograma
hist(dados$PIB, main="Valores do PIB", col = brewer.pal(n = 3, name = "Pastel1"))
hist(dados$VALOREMPENHO, main="Valores de empenho", col = brewer.pal(n = 3, name = "Paired"))
```

Busca pelos maiores valores de cada coluna numérica.
```{r}
# PIB
Mpibs =   head(dados[order(-dados$PIB),],10)
barplot(Mpibs$PIB,col=brewer.pal(n = 10, name = "Spectral"),las=2,main = "Maiores PIBS")
legend("topright",legend=Mpibs$MUNICIPIO,col = brewer.pal(n = 10, name = "Spectral"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```
```{r}
# Valores de Empenho
Mempenho = head(dados[order(-dados$VALOREMPENHO),],10)
barplot(Mempenho$VALOREMPENHO, col=brewer.pal(n = 10, name = "RdBu"),las=2,main = "Maiores Empenhos")
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "RdBu"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```

Relação entre os valores de PIB e de empenho (Cálculo da % do PIB que foi empenhado)
```{r}
dados$PROPORCAO =   dados$VALOREMPENHO  / dados$PIB 
Mprop = head(dados[order(-dados$PROPORCAO),],10)
barplot(Mprop$PROPORCAO,col=brewer.pal(n = 10, name = "Set2"),las=2,main = "Maiores Gastos em Proporção ao PIB")
legend("topright",legend=Mprop$MUNICIPIO,col = brewer.pal(n = 10, name = "Set2"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```

